### ISSUE TITLE
投稿記事へのリンクの範囲について

### ISSUE THREAD

**Issue by shimakyohsuke** [honmachi-nomi/knp-honmachi#11]
現在はタイトル部分のみがタップできるので、少し狭いように感じます。
もう少しタップできる領域を広げたいです。

<img width="342" alt="2016-11-21 13 42 19" src="https://cloud.githubusercontent.com/assets/7482290/20470996/f365f8e8-aff0-11e6-97ab-b1fba5e3db89.png">

**Comment by mismith0227** [comment]
リンク範囲広げたいっすね

**Comment by contiki9** [comment]
layout変更した
