### ISSUE TITLE
エントリー名が記事に反映されない

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi#5]
ページ設定で書いたエントリー名が記事に反映されないです。エントリー名って何を設定するものなんですかね？？

![progress2](https://cloud.githubusercontent.com/assets/11687509/20460862/eb25222e-af34-11e6-834c-545e392ee70b.png)

今のところページタイトルを編集でやるしかない？？

![2016-11-20 15 10 43](https://cloud.githubusercontent.com/assets/11687509/20460895/08a8d3c2-af35-11e6-86a2-37b62a165ddb.png)

**Comment by shimakyohsuke** [comment]
- パンくず
- OGP のタイトル
には反映されてる模様
